spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-2vfrih-kr.vpc-pub-cdb.ntruss.com:3306/team6
    username: sopt-35-team6
    password: 1q2w3e4r12!@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      show_sql: true